### ISSUE TITLE
3685 missing zp ids

### ISSUE THREAD

**Issue by nlwashington** [sba1/bio-ontology-zp#10]
today's processing has found 3685 missing ZP definitions in the [zp.annot_sourceinfo file](http://compbio.charite.de/hudson/job/zp-owl/lastSuccessfulBuild/artifact/zp.annot_sourceinfo) (12729 were mapped). 
full list coming to you in email.  here's a preview of the first 10:

<pre>
superterm1_id   subterm1_id quality_id  superterm2_id   subterm2_id modifier
ZFA:0000135     PATO:0002011            abnormal
GO:0048738      PATO:0001507            abnormal
ZFA:0005095     PATO:0001577            abnormal
ZFA:0009116 GO:0032982  PATO:0000051            normal
ZFA:0009049     PATO:0000462            abnormal
ZFA:0000076 ZFA:0009040 PATO:0000937            abnormal
GO:0032401      PATO:0002051            abnormal
ZFA:0001616     PATO:0001531            abnormal
ZFA:0001370 ZFA:0009096 PATO:0001997            abnormal
ZFA:0000138     PATO:0000462            abnormal
</pre>

**Comment by iamkoehler** [comment]
I can't find these definitions in [pheno.txt](http://zfin.org/downloads/pheno.txt) so from my perspective it is correct that those are not present in the source_info file. 
Taking your first two examples, I get no results for: 

``` bash
     grep 0000135 pheno.txt | grep 0002011
     grep 0048738 pheno.txt
```

Why are you expecting these?

**Comment by nlwashington** [comment]
according to the label of the link on the [download page](http://zfin.org/downloads/), [pheno.txt](http://zfin.org/downloads/pheno.txt) is only a subset for those genes with a curated human ortholog.  [phenotypes.txt](http://zfin.org/downloads/phenotype.txt) is everything.  our pipeline wants everything.

**Comment by iamkoehler** [comment]
Yes, this subset has been created for our pipeline, because we are only interested in those genes, where phenotype information can be transferred to human. 
pheno.txt has a different format compared to phenotype.txt and contains different information (e.g. ZDB-GENE vs. ZDB-GENO)
This is not a trivial thing. Have to think

**Comment by nlwashington** [comment]
Maybe we need to think about integrating pipelines @cmungall?

**Comment by nlwashington** [comment]
it seems that the "creating ZP ids and logical definitions" is divisible from the process of associating them with "relevant" genes.

can you separate the steps?

i would think that you can create the ZP ids from the full phenotypes.txt file, and then only pull the associations to genes from the phenos.txt file for the other part of your pipeline.  

at the moment, i only need the ZP ids and their mapping to the sextuple (and the class also defined in the zp.owl, of course).

**Comment by mellybelly** [comment]
hi all, I think that we should create a ZP (only) pipeline to be autogenerated and pushed into our import chain, that can be separate from any annotations. It would be easier to synch If we did this as part of our ontology management processes, no?

**Comment by iamkoehler** [comment]
@mellybelly not sure what exactly you mean by "our ontology managment process". can you provide details?
@nlwashington Separation seems to be the best option here. I will create one zp.owl from pheno.txt+phenotype.txt and four annotation files (pheno-pos+neg, phenotype-pos+neg)
