### ISSUE TITLE
247 unmapped ids

### ISSUE THREAD

**Issue by nlwashington** [sba1/bio-ontology-zp#11]
we are so close!

i still find 247 unmapped sextuples after your most-recent fixes.

here's the first 10:
superterm1_id   subterm1_id     quality_id      superterm2_id   subterm2_id     modifier
ZFA:0000040     ZFA:0005435     PATO:0002050                    normal
ZFA:0007037     GO:0005929      PATO:0002050                    normal
ZFA:0001108     BSPO:0000083    PATO:0001905    ZFA:0009147             normal
ZFA:0001061             PATO:0002050                    normal
ZFA:0000075             PATO:0001905    ZFA:0005177             normal
ZFA:0000538             PATO:0002050                    normal
ZFA:0000470             PATO:0001905    ZFA:0009186             normal
ZFA:0009052             PATO:0002050                    normal
ZFA:0000051             PATO:0001905    ZFA:0001617             normal
ZFA:0001617             PATO:0002050                    normal
ZFA:0009250             PATO:0002050                    normal
ZFA:0001390             PATO:0001905    ZFA:0009102             normal

rest in email.

**Comment by iamkoehler** [comment]
@nlwashington please test once more

Note that the source-information does not always exactly reflect the actual class, e.g. the source info "normal heart" would now point to a class that represents "abnormal heart". Also, for a few annotations I had to make corrections, because they are kind of wrong (e.g. the stuff mentioned in the email earlier today). If these are causing problems, let me know and I can give details.

**Comment by nlwashington** [comment]
hmmmm...  now i'm up to 338.  examples:

superterm1_id   subterm1_id quality_id  superterm2_id   subterm2_id modifier
GO:0048666      PATO:0001236            abnormal
GO:0006954      PATO:0001236            abnormal
ZFA:0009199     PATO:0000070            abnormal
ZFA:0000150 GO:0005930  PATO:0000051            abnormal
ZFA:0000001 GO:0005929  PATO:0002050            normal
ZFA:0001056 GO:0031594  PATO:0001241            abnormal
GO:0008345      PATO:0001236            abnormal
ZFA:0000013     PATO:0000051            abnormal
ZFA:0001320     PATO:0000051            abnormal
GO:0060055      PATO:0001236            abnormal
GO:0007271      PATO:0000080            abnormal

**Comment by iamkoehler** [comment]
Thanks,

there was a problem with handling multiple source-information annotations per ZP class. This should work now. Re-open in case there are more entries missing.
