### ISSUE TITLE
Make javadoc clear that we don't use pheno,txt

### ISSUE THREAD

**Issue by cmungall** [sba1/bio-ontology-zp#12]
The line here says pheno.txt

https://github.com/sba1/bio-ontology-zp/blob/5ba7d4b5a2a64f658504116db76c21e2404091db/zpgen/src/main/java/de/charite/zpgen/ZPGen.java#L51

but I don't think we use this, just phenotype.txt

cc @ybradford

**Comment by iamkoehler** [comment]
We use both and generate four different files from these. See artifacts at the [corresponding hudson job](http://compbio.charite.de/hudson/job/zp-owl/lastSuccessfulBuild/artifact/)
