### ISSUE TITLE
more missing zps

### ISSUE THREAD

**Issue by nlwashington** [sba1/bio-ontology-zp#13]
there's ~100 more missing zp ids now that zfin has moved to fish.

here's a preview:
superterm1_id   subterm1_id quality_id  superterm2_id   subterm2_id modifier
ZFA:0000717 ZFA:0009000 PATO:0000051            abnormal
ZFA:0000008 GO:0061351  PATO:0000057            normal
ZFA:0000155 ZFA:0009116 PATO:0000967            abnormal
ZFA:0000435     PATO:0000937            abnormal
ZFA:0000123 MPATH:218   PATO:0000467            abnormal
ZFA:0005124     PATO:0000644            abnormal

**Comment by iamkoehler** [comment]
Seems to be fixed with latest [run of hudson job](https://compbio.charite.de/hudson/job/zp-owl/lastSuccessfulBuild/artifact/).
