### ISSUE TITLE
Set ontology ID

### ISSUE THREAD

**Issue by cmungall** [sba1/bio-ontology-zp#6]
Currently the zp.owl file has the header

```
Ontology(<http://purl.obolibrary.org/obo/>
```

This should have an ontology URI that is correct, and ideally additional metadata

We have been using `http://purl.obolibrary.org/obo/upheno/zp.owl`

The versionIRI can go here. Should this be set by the hudson job, or downstream in svn?

We could also add information about when the info was pulled from ZFIN

**Comment by iamkoehler** [comment]
Please check the latest version at http://compbio.charite.de/hudson/job/zp-owl/ . It should contain the correct ontology IRI and version IRI. 

The date on which the ZFIN data has been pulled is the same as the version IRI now, so I have not added an additional field. Does this make sense?
