### ISSUE TITLE
many zp id decomps missing

### ISSUE THREAD

**Issue by nlwashington** [sba1/bio-ontology-zp#8]
i don't think the zp.annot_sourceinfo is quite right.

for example, i have an old version of the mapping file that defines:

<pre>
ZP:0000028  abnormal(ly) disrupted endoderm development GO:0007492      PATO:0001507    PATO:0000460
ZP:0000123  abnormal(ly) absent mouth   ZFA:0000547     PATO:0000462    PATO:0000460        
</pre>

but these are completely missing in the new file zp.annot_sourceinfo

is that expected?  there seem to be many missing. 

i count ~5200 that are in both my old mapping file and the new one on hudson, ~1200 unique to the new file you've made, and 5563 only in my old one!  can you bring these back @drseb ?

**Comment by nlwashington** [comment]
let me know if you need my old file for comparison.

**Comment by iamkoehler** [comment]
You are right, but it seems that only the zp.annot_sourceinfo has an error. The annotation between ZDB-GENE-000201-18 and ZP:0000028 is present in zp.annot and the class ZP:0000028 is present in zp.owl.
I am investigating. (Please note, that zp.owl has this information as OWL Annotation - maybe you want to use this instead.)
