### ISSUE TITLE
process the "normal" phenotypes 

### ISSUE THREAD

**Issue by nlwashington** [sba1/bio-ontology-zp#9]
the phenotypes that are marked as "normal" are not currently used to generate any parallel "abnormal" phenotypes.  

i would like to be able to make not-abnormal associations, but this would require the abnormal phenotypes be available. there's currently ~ 1800 of these.

**Comment by iamkoehler** [comment]
@cmungall do you have any thoughts on this? I am not sure what you are trying to achieve, but inferences over normal phenotype classes will not work well with the abnormal phenotype classes from other organisms. I think I need more input on the downstream usage of this data.

**Comment by cmungall** [comment]
In theory precomposing normal phenotype classes in ZP should be safe, the resulting subclass hierarchy should be disjoint with the abnormal one. However, we would need to do some extensive testing to be sure.

A different approach would be to creating a NegatedAnnotation for every normal phenotype, e.g. `gene NOT has_phenotype abnormal X`.

**Comment by nlwashington** [comment]
Yes, the latter is what I was proposing.... Basically for any annotations
in the data marked with a normal qualifier, create a term for the abnormal
version of it, and we would make "not" annotations against the abnormal
term.

**Comment by iamkoehler** [comment]
@nlwashington This sounds reasonable. But I will have to change the annotation file (zp.annot) format, because we need the additional qualifier in there. 
I will thus not create classes for normal phenotypes.

**Comment by iamkoehler** [comment]
So implemented the following: I parse "normal annotations", for example when a curator stated
that upon mutating gene X the heart was found to be normal. This will
then create a negative annotation, i.e. that X is NOT causing abnormal heart.
The negative annotations are stored in a [separate file](http://compbio.charite.de/hudson/job/zp-owl/lastSuccessfulBuild/artifact/zp.annot_negative)

Does this look ok for you? Let me know if you find any problems.
